### PR TITLE
Update Assay File Headers

### PR DESCRIPTION
**Pull request by HLWeil**
`isa.assay.xlsx` file headers have changed since `Swate 0.5.0`. Headers in this sample assay file were updated to stay compatible.

### CODE REVIEW

**Comment by Brilator** [comment]
Merged, but I'd suggest to shut this ARC down here and keep the one in the ARC GitLab updated. 
https://gitlab.nfdi4plants.de/martinkuhl/samplearc_rnaseq

**Comment by HLWeil** [comment]
Sure thing, can you send me a link for that one? I have another bugfix for the investigation file locally

**Comment by Brilator** [comment]
I did above.

**Comment by HLWeil** [comment]
Whoops 🤦‍♂️

**Pull request merged**
